### ISSUE TITLE
KeyValue Replicas > 1

### ISSUE THREAD

**Issue by ondi** [ripienaar/nats-kv-leader-elect#2]
Hi!
Should it work with nats.KeyValueConfig{Replicas: 3}?
Even with Replicas: 2 Nats log flooding
```
Resetting stream cluster state for '$G > KV_election'
```
Update(key, ...) method return timeout.
But everything fine with Replicas: 1

**Comment by ripienaar** [comment]
Yes, works for me with R3.  The resetting log is probably a inconsistency in the nats server and so the election bucket isnt available, thats why it fails.

**Comment by ripienaar** [comment]
I think actually this does surface a bug in clustered mode, will investigate

**Comment by ripienaar** [comment]
You can follow along here https://github.com/nats-io/nats-server/issues/2666

**Comment by ripienaar** [comment]
This works against nightly now iwth > R1
